name: Lint

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: PHPCodeSniffer
        uses: rtCamp/action-phpcs-inspection@v1.0.0
